### ISSUE TITLE
Error at flutter/ephemeral/.plugin_symlinks/quick_scanner/windows/CMakeLists.txt:13 

### ISSUE THREAD

**Issue by aexces** [woodemi/quick_scanner#6]
## Debug
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
NUGET.EXE not found.
CMake Error at flutter/ephemeral/.plugin_symlinks/quick_scanner/windows/CMakeLists.txt:13 (message):
Please install this executable, and run CMake again.

Exception: Unable to generate build files
Exited (sigterm)

## Issue
Dependency that isn't part of the standard tools required by Flutter (NuGet). If that plugin doesn't tell you in its README that you need to install that extra dependency, you should report that to the developer of the plugin.

**Comment by aexces** [comment]
[Duplicate of #95898](https://github.com/flutter/flutter/issues/95898#issue-1089804811)

**Comment by Sunbreak** [comment]
You'll need `nuget` for C++/WinRT

Ref: https://github.com/woodemi/quick_notify/discussions/8
